alias pys="python -m http.server 9191"
alias gitau="git update-index --assume-unchanged"
alias logadog="git log --color --graph --all --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit ; echo \"A parting dog for your troubles: 🐕\""
alias gits="git status"
alias gitc="git checkout"
alias gitb="git branch"
