source ~/.shell/zsh/remote/zsh-snap/znap.zsh
source ~/.shell/zsh/znap-plugins.zsh

source ~/.shell/alias.sh
source ~/.shell/path.sh

source ~/.shell/zsh/functions.zsh

znap prompt
znap eval starship 'starship init zsh'

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
