source ~/.shell/zsh/znap-setup.zsh

source ~/.zsh-plugins/zsh-snap/znap.zsh

source ~/.shell/zsh/znap-plugins.zsh

source ~/.shell/zsh/functions.zsh
source ~/.shell/functions.sh
source ~/.shell/aliases.sh
source ~/.shell/variables.sh
source ~/.shell/path.sh

znap eval starship 'starship init zsh'
znap prompt

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
