source ~/.shell/zsh/znap-setup.zsh
source ~/.shell/zsh/remote/zsh-snap/znap.zsh
source ~/.shell/zsh/znap-plugins.zsh

source ~/.shell/alias.sh
source ~/.shell/path.sh

znap eval starship 'starship init zsh'
znap prompt

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
